#!/bin/bash
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms1.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms2.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms3.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms4.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms5.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms6.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms7.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms8.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms9.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms10.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms11.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms12.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms13.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms14.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms15.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms16.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms17.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms18.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms19.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms20.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms21.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms22.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms23.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms24.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms25.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms26.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms27.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms28.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms29.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms30.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms31.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms32.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms33.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms34.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms35.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms36.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms37.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms38.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms39.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms40.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms41.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms42.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms43.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms44.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms45.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms46.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms47.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms48.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms49.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms50.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms51.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms52.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms53.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms54.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms55.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms56.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms57.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms58.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms59.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms60.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms61.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms62.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms63.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms64.txt