#!/bin/bash
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms1wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms2wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms3wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms4wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms5wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms6wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms7wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms8wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms9wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms10wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms11wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms12wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms13wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms14wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms15wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms16wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms17wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms18wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms19wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms20wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms21wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms22wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms23wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms24wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms25wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms26wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms27wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms28wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms29wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms30wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms31wr.txt
terminal --hold -e sh -x ssh -t mdanne1@ubuntu.cs.mcgill.ca java TestClient 512proj/test/testmultiplerms32wr.txt